### ISSUE TITLE
Cannot call value of non-function type 'GIDSignIn'

### ISSUE THREAD

**Issue by ruddyVDS** [rudrankriyam/Ellifit#1]
Hi!

Thank you to share this tutorial.

I'm getting an error when I try to add:
    GIDSignIn.sharedInstance().clientID = FirebaseApp.app()?.options.clientID
into the setupAuthentication function.

Cannot call value of non-function type 'GIDSignIn'

Any idea?

regards
Ruddy

**Comment by Scootworks** [comment]
hi Ruddy

Same for me, also for the AuthenticationViewModel.

**Comment by rudrankriyam** [comment]
Hi @ruddyVDS and @Scootworks,

In the latest version of the SDK, they've changed the way it works. You can have a look here - 

https://developers.google.com/identity/sign-in/ios/sign-in

I'll update the project soon with the latest SDK.

**Comment by rudrankriyam** [comment]
It is now something like - 

```swift 
 GIDSignIn.sharedInstance.signIn(with: signInConfig, presenting: self) { user, error in
}
```

**Comment by Scootworks** [comment]
> It is now something like -
> 
> ```swift
>  GIDSignIn.sharedInstance.signIn(with: signInConfig, presenting: self) { user, error in
> }
> ```

got it, indeed. thanks a lot

**Comment by rudrankriyam** [comment]
Hi, @Scootworks and @ruddyVDS,

I've updated the project to use the latest Firebase and Google Sign-In using Swift Package Manager. Do let me know if it works for you. 

Cheers!
